query getProduct($slug: ID!, $siteReviews_page: Int = 1, $siteReviews_perPage: Int = 10, $siteReviews_rating: Int = 0, $siteReviews_hasContent: Boolean = true) {
  product(id: $slug, idType: SLUG) {
    name
    type
    databaseId
    id
    metaData {
      id
      key
      value
    }
    siteReviews(page: $siteReviews_page, perPage: $siteReviews_perPage, rating: $siteReviews_rating, hasContent: $siteReviews_hasContent) {
      pageInfo {
        total
        totalPages
      }
      reviews {
        content
        rating
        author
        response
        sourceLink
        avatar
        contextQuestionAnswers
        date
        negativeNotes
        positiveNotes
        photoCount
        product_id
      }
      averageRating
      ratingsBreakdown {
        rating
        count
        percentage
      }
      totalReviews
    }
    slug
    sku
    description
    rawDescription: description(format: RAW)
    shortDescription
    ...ProductWithAttributes
    ...ProductCategories
    ...Terms
    ...SimpleProduct
    ...VariableProduct
    ...ExternalProduct
    related(first: 5) {
      nodes {
        ...SimpleProduct
        ...VariableProduct
        ...ExternalProduct
      }
    }
    reviews {
      averageRating
      edges {
        rating
        node {
          ...Comment
        }
      }
    }
  }
}

fragment ProductWithAttributes on ProductWithAttributes {
  attributes {
    nodes {
      ...ProductAttribute
    }
  }
}

fragment ProductAttribute on ProductAttribute {
  variation
  name
  id
  options
  label
  scope
  ... on GlobalProductAttribute {
    terms(where: { orderby: MENU_ORDER, order: ASC }) {
      nodes {
        name
        slug
        taxonomyName
        databaseId
      }
    }
  }
}

fragment Comment on Comment {
  content
  id
  date
  author {
    node {
      name
      avatar {
        url
      }
    }
  }
}
